const { Double } = require('bson');
const mongoose = require('mongoose');

let ResumeSchemas = mongoose.Schema({
    firstname:{
        type:String,
    },
    lastname:{
        type:String,
    },
    title:{
        type:String,
    },
    address:{
        type:String,
    },
    phone:{
        type:String,
    },
    email:{
        type:String,
    },
    links:[{
        url:{type:String},
        name:{type:String},
    }],
    education:[
        {
            Institutename:{
                type:String,
                
            },
            degree:{
                type:String,
                
            },
            location:{
                type:String
            },
            program:{
                type:String,
            },
            gpa:{
                type:Number
            },
            start:{
                type:String
            },
            end:{
                type:String
            }
        }
    ],
    experience:[
        {
            employer:{
                type:String
            },
            jobtitle:{
                type:String
            },
            start:{
                type:String
            },
            end:{
                type:String
            },
            location:{
                type:String
            },
            discription:{
                type:String
            }
        }
    ],
    skills:{
        programinglanguages:[
            {
                type:String
            }
        ],
        libraries:[
            {
                type:String
            }
        ],
        tools:[
            {
                type:String
            }
        ],
        databases:[
            {
                type:String
            }
        ]
    },
    projects:[
        {
            name:{
                type:String
            },
            description:{
                type:String
            },
            projectlink:{
                type:String
            },
            technology:{
                type:String
            }
        }
    ],
    honors:[{
            type:String
    }],
    user_id:{
        type:mongoose.Schema.ObjectId
    }
});

module.exports = ResumeSchemas = mongoose.model('resume',ResumeSchemas);